http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "ip:port","ip:port","ip:port" ]
config.reload.automatic: true
pipeline.separate_logs: true
path.logs: /usr/share/logstash/logs
log.format: json
config.reload.automatic: true
config.reload.interval: 3s
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.password: password
#xpack.management.enabled: true
#xpack.management.elasticsearch.hosts: [ "ip:port","ip:port","ip:port" ]
#xpack.management.pipeline.id: ["MES","Nginx"]
#xpack.management.logstash.poll_interval: 5s
#xpack.management.elasticsearch.username: logstash_system
#xpack.management.elasticsearch.password: password
